"""The owner's list of possible reach partners (fan pages, creators, communities) for each demo business.

These are SCENARIO INPUTS, invented for the demo (the owner would type or paste their own list); none of them is a real account.
Fields mirror contract v2 `reach_candidates`.
"""
EXTRAS = {
    "boxbox": {"city": "Pune", "ships_to": "India", "topics": ['f1', 'motorsport'], "growth_minutes_per_week": 180, "order_link": 'link in bio', "payment": 'UPI',
               "reach_candidates": [{'partner_id': 'rp_bb_1',
  'name': 'Pune F1 Fans (fan page)',
  'type': 'fan_page',
  'topics': ['f1'],
  'city': 'Pune',
  'followers': 8200,
  'avg_comments_per_post': 46,
  'avg_shares_per_post': 30,
  'cost_inr': 0},
 {'partner_id': 'rp_bb_2',
  'name': 'Grid Sketches (F1 illustrator)',
  'type': 'creator',
  'topics': ['f1', 'art'],
  'city': 'Mumbai',
  'followers': 12000,
  'avg_comments_per_post': 80,
  'avg_shares_per_post': 40,
  'cost_inr': 0},
 {'partner_id': 'rp_bb_3',
  'name': 'Campus Motorsport Club (college community)',
  'type': 'community',
  'topics': ['motorsport'],
  'city': 'Pune',
  'followers': 1900,
  'avg_comments_per_post': 22,
  'avg_shares_per_post': 18,
  'cost_inr': 0},
 {'partner_id': 'rp_bb_4',
  'name': 'Lights Out India (national fan page)',
  'type': 'fan_page',
  'topics': ['f1'],
  'city': None,
  'followers': 41000,
  'avg_comments_per_post': 35,
  'avg_shares_per_post': 12,
  'cost_inr': 1500},
 {'partner_id': 'rp_bb_5',
  'name': 'Pune Streetwear Collective (community)',
  'type': 'community',
  'topics': ['streetwear'],
  'city': 'Pune',
  'followers': 5000,
  'avg_comments_per_post': 10,
  'avg_shares_per_post': 5,
  'cost_inr': 0}]},
    "homebaker": {"city": "Pune", "ships_to": 'Pune, within 8 km of Kothrud', "topics": ['baking', 'desserts', 'gifting'], "growth_minutes_per_week": 120, "order_link": 'WhatsApp order form', "payment": 'UPI',
                  "reach_candidates": [{'partner_id': 'rp_hb_1',
  'name': 'Neighbourhood parents group (WhatsApp community)',
  'type': 'community',
  'topics': ['parenting', 'gifting'],
  'city': 'Pune',
  'followers': 900,
  'avg_comments_per_post': 25,
  'avg_shares_per_post': 12,
  'cost_inr': 0},
 {'partner_id': 'rp_hb_2',
  'name': 'Pune dessert reviewer (creator)',
  'type': 'creator',
  'topics': ['desserts', 'baking'],
  'city': 'Pune',
  'followers': 15000,
  'avg_comments_per_post': 60,
  'avg_shares_per_post': 25,
  'cost_inr': 0},
 {'partner_id': 'rp_hb_3',
  'name': 'Office foodies group (community)',
  'type': 'community',
  'topics': ['food'],
  'city': 'Pune',
  'followers': 3000,
  'avg_comments_per_post': 15,
  'avg_shares_per_post': 6,
  'cost_inr': 0},
 {'partner_id': 'rp_hb_4',
  'name': 'Food influencer with paid shoutouts',
  'type': 'creator',
  'topics': ['desserts'],
  'city': 'Mumbai',
  'followers': 90000,
  'avg_comments_per_post': 120,
  'avg_shares_per_post': 40,
  'cost_inr': 3000}]},
}
